### ISSUE TITLE
IBDesignable ignores some views has skeleton 

### ISSUE THREAD

**Issue by Linkadi98** [Juanpe/SkeletonView#179]
### What did you do?

I have set skeleton and it also worked fine

### What did you expect to happen?

Normal behavior of skeleton

### What happened instead?

Xcode ignored some views had skeleton and throw some warning like IBDesignable ignoring user ... runtime and can not set value for views. I have some labels which have skeleton and seems like skeleton is ignored by xcode and produce a problem that label can not have been set value (not the default values)

### Steps to reproduce the behavior

Well I have returned back to the old version of skeleton but it produce other problem, that is table view now has weird behaviors: tableview always be pulled down 2 cell and therefore I can not see the content of those cells and have to scroll up to see it, really weird.

### SkeletonView Environment

**SkeletonView version: 1.7**
**Xcode version:10.2.1**
**Swift version:5.1**

**Comment by Juanpe** [comment]
Hi @Linkadi98, it seems is a problem of XCode and Cocoapods, using IBDesignables of 3rd party libraries. 
[Cocopoads repo](https://github.com/CocoaPods/CocoaPods/issues/7606) you can see more info.

Another possible solution is to use Carthage or SPM instead.

Since it's an issue that we can't fix, I'm going to close it.

Thanks for reporting
