### ISSUE TITLE
Multiline text label displays as one big rectangle instead of multiple rectangles representing lines

### ISSUE THREAD

**Issue by MervinDelfin** [Juanpe/SkeletonView#194]
⚠️ Please fill out this template when filing an issue.

### What did you do?

*Please replace this with what you did.*

### What did you expect to happen?

*Please replace this with what you expected to happen.*

### What happened instead?

*Please replace this with of what happened instead.*  

### Steps to reproduce the behavior

*Please replace this with the steps to reproduce the behavior.*

### SkeletonView Environment

**SkeletonView version:**
**Xcode version:**
**Swift version:**

**Comment by dougdss** [comment]
In my case, this is happening inside UITableViewCells.

**Comment by mohpor** [comment]
@dougdss Your issue is old enough that I think you'v already found the solution. But for the sake of people who encounter this issue:

This issue is related to layouting of the view you are trying to show skeleton on. Skeleton view doesn't try to layout the views before adding skeleton layers. Therefore, you need to make sure your view has appropriate layout before starting the skeleton. The best thing you can do, is to make sure you call `view.layoutIfNeeded()` before calling start. This way the correct size (which might differ from what is in your nib file) will be calculated for the views.

@Juanpe I guess this stale bot is counter productive for this repo. Issues got closed without an appropriate response and get lost in the pool of stale-closed and makes people want to create new issues.

**Comment by Juanpe** [comment]
Hi! 

Could you provide more info about when you are calling to show the skeleton? Thanks


@mohpor, about the bot, I think the problem is not the bot, it's the config that it had. I modified the config a few days ago. Now, the bot will close issues with the "awaiting user input" label.

**Comment by mohpor** [comment]
> Hi!
> 
> Could you provide more info about when you are calling to show the skeleton? Thanks
> 
> @mohpor, about the bot, I think the problem is not the bot, it's the config that it had. I modified the config a few days ago. Now, the bot will close issues with the "awaiting user input" label.

Perfect

**Comment by Juanpe** [comment]
@MervinDelfin any update?

**Comment by yliu342** [comment]
I had a similar issue. The Label inside a tableview cell just rendered as a big block of rectangle. I don't use story board or nib but all constraints are added programmatically.

**Comment by yliu342** [comment]
The structure for my cell is I have a cell the cell's contentview contains a subview view. All labels imageviews etc are inside this subview.  

What I've tried is in the subview's `layoutSubviews` I tried to call `layoutSkeletonIfNeeded` but it does not solve the issue

**Comment by trm36** [comment]
I have this issue too.

**Comment by PramodShukla10** [comment]
any one get solution?
