### ISSUE TITLE
Tableview alway show header and footer Skeletonview when call showAnimatedGradientSkeleton

### ISSUE THREAD

**Issue by kidS2ran** [Juanpe/SkeletonView#282]
when i call showAnimatedGradientSkeleton

tableview alway show header and footer how can i remove

### SkeletonView Environment

**SkeletonView version:** lastest
**Xcode version:** 11.4
**Swift version:** 5

**Comment by AprilYoungs** [comment]
@kidS2ran I got the same issue, if you don't have section header or footer, don't use this protocol `SkeletonTableViewDelegate`, and the header and footer will be gone

**Comment by Juanpe** [comment]
Exactly, as. @AprilYoungs said, if you don't have a section header or footer, you don't need to conform to `SkeletonTableViewDelegate` protocol :)

Since this issue seems solved, I'm going to close it. But, please, feel free to create a new one if you still face the same problem or find another one.

Thanks for using SkeletonView

**Comment by mparmar-covantex** [comment]
> @kidS2ran I got the same issue, if you don't have section header or footer, don't use this protocol SkeletonTableViewDelegate, and the header and footer will be gone

Works for me, Thanks. @AprilYoungs cc: @Juanpe
