### ISSUE TITLE
Multiple errors after install 1.8.6 using Cocoapods

### ISSUE THREAD

**Issue by ricardoisidro** [Juanpe/SkeletonView#300]
# What did you do?

Install SkeletonView on my project with Cocoapods and build the project.

### What did you expect to happen?

Build the project even if SkeletonView is not used yet.

### What happened instead?

Some errors occurs and project cannot be builded.

![image](https://user-images.githubusercontent.com/26470470/86487913-fed3ff00-bd24-11ea-9a81-6443db1f60e6.png)

### Steps to reproduce the behavior

1. `pod "SkeletonView", '1.8.6'`
2. `pod install`
3. Build project

### SkeletonView Environment

**SkeletonView version: 1.8.6**
**Xcode version: 11.3**
**Swift version: 4.2**

**Comment by phynet** [comment]
Hi, it's a strange thing for sure, even when you're telling you're using swift version 4.2 the compiler says otherwise. Did you use the migrator tool recently? 

Have you tried any of these:
1.- I'm assuming you have installed the pod in a project started from scratch. Did you open `.xcworkspace` instead of `xcodeproj`, right?
2.- Try to do a clean and delete derived data and open the project again
3.- Try to do a `pod repo update` and `pod install` (you can try use the newer version 1.8.7) 

Good luck.

**Comment by ricardoisidro** [comment]
Solved!

The problem was inside podfile `post_install` script, because `SWIFT_VERSION` `build_setting` was being overwritten to 4.0.

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
    end
end
```
After change it to 4.2, everything worked fine.

**Comment by phynet** [comment]
Good to hear, the compiler usually knows what he’s doing 😆
